language: cpp
git:
  depth: 1
notifications:
  email: false

_anchors:
  - &refreshpath eval $(powershell -NonInteractive -Command 'write("export PATH=`"" + ([Environment]::GetEnvironmentVariable("PATH","Machine") + ";" + [Environment]::GetEnvironmentVariable("PATH","User")).replace("\","/").replace("C:","/c").replace(";",":") + ":`$PATH`"")')

jobs:
  include:
    - name: Windows, no-SGCT
      if: branch IN (develop, master)
      os: windows
      env: VISCOM_SGCT="OFF" VISCOM_LOCAL="ON" CMAKE_BUILDER="Visual Studio 15 2017 Win64"
      before_install: &windowsbefore_install
        - choco install python -y
        - cmd //C 'RefreshEnv.cmd & pip install conan'
      script: &windows_script
        - mkdir build && cd build
        - *refreshpath
        - conan remote add arsen-studio https://api.bintray.com/conan/arsen-studio/arsen-deps
        - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
        - conan install --build=missing -s compiler='Visual Studio' -s compiler.version=14 --install-folder=./fwcore ..
        - cmake -G "${CMAKE_BUILDER}" -D VISCOM_USE_SGCT:BOOL=${VISCOM_SGCT} -D VISCOM_LOCAL_ONLY:BOOL=${VISCOM_LOCAL} -D SGCT_INCLUDE_DIRECTORY="${SGCT_ROOT_DIR}/include" -D SGCT_DEBUG_LIBRARY="${SGCT_ROOT_DIR}/lib/sgctd.lib" -D SGCT_RELEASE_LIBRARY="${SGCT_ROOT_DIR}/lib/sgct.lib" ..
        - *refreshpath
        - cmake --build .
    - name: Windows, SGCT, local only
      os: windows
      env: VISCOM_SGCT="ON" VISCOM_LOCAL="ON" SGCT_ROOT_DIR="../deps/sgct_install"  CMAKE_BUILDER="Visual Studio 15 2017 Win64"
      before_install: *windowsbefore_install
      before_script: &sgctbefore_script
        - mkdir -p deps/sgct
        - cd deps/sgct
        - git clone --recursive https://github.com/opensgct/sgct.git .
        - git checkout c487fe9d778a730125b72027b2da5588a664d01b
        - git submodule update --init --recursive
        - mkdir build && cd build
        - cmake -E env cmake -G "${CMAKE_BUILDER}" -D JPEG_TURBO_WITH_SIMD=OFF -D SGCT_INSTALL=ON -D CMAKE_INSTALL_PREFIX="../../sgct_install" ..
        - cmake --build . --target install
        - cd ../../..
        - cd deps/sgct_install/lib
        - dir
        - cd ../../..
      script: *windows_script
    - name: Windows, SGCT
      if: branch = master
      os: windows
      env: VISCOM_SGCT="ON" VISCOM_LOCAL="OFF" SGCT_ROOT_DIR="../deps/sgct_install"  CMAKE_BUILDER="Visual Studio 15 2017 Win64"
      before_install: *windowsbefore_install
      before_script: *sgctbefore_script
      script: *windows_script
    - name: Linux (GCC), no-SGCT
      if: branch IN (develop, master)
      os: linux
      dist: xenial
      env: VISCOM_SGCT="OFF" VISCOM_LOCAL="ON" VISCOM_COMPILER_ENV="CC=gcc-8 && CXX=g++-8" CMAKE_BUILDER="Unix Makefiles" LIB_PREFIX="lib" LIB_ENDING="a"
      addons: &linuxaddons
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8
          packages:
            - g++-8
            - clang-8
            - libc++-8-dev
            - libc++abi-8-dev
            - xorg-dev
            - libgl1-mesa-dev
            - libxcb-glx0-dev
            - libglu-dev
            - libxi-dev
            - libxcursor-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxxf86vm-dev
            - python3
            - python3-setuptools
            - python3-pip
      before_install: &linuxbefore_install
        - eval "${VISCOM_COMPILER_ENV}"
        - pip3 install conan
        - conan remote add arsen-studio https://api.bintray.com/conan/arsen-studio/arsen-deps
        - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
      script: &linux_script
        - mkdir build && cd build
        - conan install --build=missing --install-folder=./fwcore -s compiler.libcxx=libstdc++11 ..
        - cmake -G "${CMAKE_BUILDER}" -D VISCOM_USE_SGCT:BOOL=${VISCOM_SGCT} -D VISCOM_LOCAL_ONLY:BOOL=${VISCOM_LOCAL} -D SGCT_INCLUDE_DIRECTORY="${SGCT_ROOT_DIR}/include" -D SGCT_DEBUG_LIBRARY="${SGCT_ROOT_DIR}/lib/${LIB_PREFIX}sgctd.${LIB_ENDING}" -D SGCT_RELEASE_LIBRARY="${SGCT_ROOT_DIR}/lib/${LIB_PREFIX}sgct.${LIB_ENDING}" -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON ..
        - cmake --build .
    - name: Linux (GCC), SGCT, local only
      if: branch = master
      os: linux
      dist: xenial
      env: VISCOM_SGCT="ON" VISCOM_LOCAL="ON" VISCOM_COMPILER_ENV="CC=gcc-8 && CXX=g++-8" CMAKE_BUILDER="Unix Makefiles" SGCT_ROOT_DIR="../deps/sgct_install" LIB_PREFIX="lib" LIB_ENDING="a"
      addons: *linuxaddons
      before_install: *linuxbefore_install
      before_script: *sgctbefore_script
      script: *linux_script
    - name: Linux (GCC), SGCT
      os: linux
      dist: xenial
      env: VISCOM_SGCT="ON" VISCOM_LOCAL="OFF" VISCOM_COMPILER_ENV="CC=gcc-8 && CXX=g++-8" CMAKE_BUILDER="Unix Makefiles" SGCT_ROOT_DIR="../deps/sgct_install" LIB_PREFIX="lib" LIB_ENDING="a"
      addons: *linuxaddons
      before_install: *linuxbefore_install
      before_script: *sgctbefore_script
      script: *linux_script
    - name: Linux (clang), no-SGCT
      if: branch IN (develop, master)
      os: linux
      dist: xenial
      env: VISCOM_SGCT="OFF" VISCOM_LOCAL="ON" VISCOM_COMPILER_ENV="CC=clang-8 && CXX=clang++-8" CMAKE_BUILDER="Unix Makefiles"
      addons: *linuxaddons
      before_install: *linuxbefore_install
      script: *linux_script
    - name: Linux (clang), SGCT, local only
      if: branch = master
      os: linux
      dist: xenial
      env: VISCOM_SGCT="ON" VISCOM_LOCAL="ON" VISCOM_COMPILER_ENV="CC=clang-8 && CXX=clang++-8" CMAKE_BUILDER="Unix Makefiles" SGCT_ROOT_DIR="../deps/sgct_install" LIB_PREFIX="lib" LIB_ENDING="a"
      addons: *linuxaddons
      before_install: *linuxbefore_install
      before_script: *sgctbefore_script
      script: *linux_script
    - name: Linux (clang), SGCT
      if: branch = master
      os: linux
      dist: xenial
      env: VISCOM_SGCT="ON" VISCOM_LOCAL="OFF" VISCOM_COMPILER_ENV="CC=clang-8 && CXX=clang++-8" CMAKE_BUILDER="Unix Makefiles" SGCT_ROOT_DIR="../deps/sgct_install" LIB_PREFIX="lib" LIB_ENDING="a"
      addons: *linuxaddons
      before_install: *linuxbefore_install
      before_script: *sgctbefore_script
      script: *linux_script
    - name: MacOS X, no-SGCT
      os: osx
      osx_image: xcode11.6
      before_install: &macbefore_install
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install python3
        - CC=clang && CXX=clang++
        - pip install conan
        - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
      script: &osx_script
        - mkdir build && cd build
        - conan install --build=missing --install-folder=./fwcore ../conanfile-osx.txt
        - cmake -G "Xcode" -D VISCOM_CONAN_BUILD_ALL:BOOL=ON -D VISCOM_USE_SGCT:BOOL=OFF -D VISCOM_LOCAL_ONLY:BOOL=ON ..
        - cmake --build .
